name: LINE通知送信

on:
  workflow_dispatch:

jobs:
  send_line_notify:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Pythonセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run LINE notify script
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          LINE_USER_IDS: ${{ secrets.LINE_USER_IDS }}
        run: |
          echo "🔔 Start LINE notify script"
          python send/send_line_message0.py
          echo "✅ LINE notify script finished"